//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2017-04-11 10:48:28 by mayday
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{    

    public class JFLoanNumber
    {
        
        /// <summary>
        /// 
        /// </summary>        
        public int Id { get; set; }
        
        /// <summary>
        /// RJB借款标ID
        /// </summary>        
        public int? LoanId { get; set; }
        
        /// <summary>
        /// RJB标号
        /// </summary>        
        public string RJBLoanNumber { get; set; }
        
        /// <summary>
        /// 金服标号
        /// </summary>        
        public string JFLoanNumber { get; set; }
        
        /// <summary>
        /// 金服服务费
        /// </summary>        
        public decimal JFServiceFee { get; set; }
        
        /// <summary>
        /// 线下费率
        /// </summary>        
        public decimal OfflineRate { get; set; }
        
        /// <summary>
        /// 是否续贷
        /// </summary>        
        public bool IsRenewLoan { get; set; }
         

		/// <summary>
        /// 更新一条数据
        /// </summary>
        public bool ModifyRepaymentPlanSplit(RepaymentPlanSplitModel model)
        {
			 
			var sql = "UPDATE dbo.JFLoanNumber SET Id=@Id,LoanId=@LoanId,RJBLoanNumber=@RJBLoanNumber,JFLoanNumber=@JFLoanNumber,JFServiceFee=@JFServiceFee,OfflineRate=@OfflineRate,IsRenewLoan=@IsRenewLoan,";
			var paras = {new SqlParameter(@Id, SqlDbType.int){Value= model.Id}new SqlParameter(@LoanId, SqlDbType.int){Value= model.LoanId}new SqlParameter(@RJBLoanNumber, SqlDbType.varchar){Value= model.RJBLoanNumber}new SqlParameter(@JFLoanNumber, SqlDbType.varchar){Value= model.JFLoanNumber}new SqlParameter(@JFServiceFee, SqlDbType.decimal){Value= model.JFServiceFee}new SqlParameter(@OfflineRate, SqlDbType.decimal){Value= model.OfflineRate}new SqlParameter(@IsRenewLoan, SqlDbType.bit){Value= model.IsRenewLoan}};
		}
    }
}

