
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2017-04-14 17:55:43 by mayday
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.IService
{    
	/// <summary>
    /// 订单业务接口
    /// </summary>
	public interface IOrderManage : IRepository<Domain.Card_Order>
    {

    }
}
