
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2017-04-14 17:56:13 by mayday
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Service.IService;

namespace Service.ServiceImp
{  
	public class OrderManage : RepositoryBase<Domain.Card_Order>, IOrderManage
    {

    }
}